[project]
name = "state-embedding"
version = "0.1.0"
description = "Pretrain state embeddings"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "gymnasium[all]>=1.1.1",
    "stable-baselines3>=2.6.0",
]

[project.scripts]
hello = "state_embedding:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.6.7",
]
